# Generated by Django 5.1.1 on 2025-10-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Enter discount as percentage, e.g., 10 for 10%', max_digits=5),
        ),
    ]
