# Generated by Django 5.1.1 on 2025-10-27 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='is_approved',
            new_name='is_verified',
        ),
    ]
